sudo: false
language: android

env:
  global:
    - ANDROID_API_LEVEL=24
    - ANDROID_EMULATOR_API_LEVEL=22
    - ANDROID_BUILD_TOOLS_VERSION=26.0.2
    - ANDROID_ABI=armeabi-v7a
    - ANDROID_TAG=google_apis

before_script:
  - echo no | android create avd --force -n test -t \"android-$ANDROID_EMULATOR_API_LEVEL\" --abi $ANDROID_ABI --tag $ANDROID_TAG
  - emulator -avd test -no-audio -no-window &
  - android-wait-for-emulator
  - sleep 180
  - adb devices
  - adb shell input keyevent 82 &

before_install:
  - chmod +x gradlew

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"

android:

  components:
    - tools
    - platform-tools
    - tools
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - android=$ANDROID_API_LEVEL
    - android=$ANDROID_EMULATOR_API_LEVEL

    # Additional components
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # For emulator
    - sys-img-armeabi-v7a-google_apis-$ANDROID_EMULATOR_API_LEVEL

script:
  - ./gradlew clean build connectedAndroidTest -PdisablePreDex --stacktrace

notifications:
  email: true